- type: job
  id: BkmVirologist
  name: job-name-BkmVirologist
  description: job-description-BkmVirologist
  playTimeTracker: JobBkmVirologist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 
  startingGear: BkmVirologistGear
  icon: "JobIconVirologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Virology
  extendedAccess:
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
    #start-backmen: surgery
    #- type: CPRTraining
    - type: SurgerySpeedModifier
      SpeedModifier: 1.75
    #end-backmen: surgery
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: BkmVirologistGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    id: VirologistPDA
