- type: job
  id: Student
  name: job-name-student
  description: job-description-student
  playTimeTracker: JobStudent
  startingGear: StudentGear
  setPreference: false
  canBeAntag: false
  icon: "JobIconUnknown" # TODO
  supervisors: job-supervisors-teachers

- type: startingGear
  id: StudentGear
  equipment:
    jumpsuit: ClothingUniformSchoolGakuranBlack
    id: StudentIDCard
    shoes: ClothingShoesColorBlack
    back: ClothingBackpack
  #innerClothingSkirt: UniformSchoolgirlDusk
  #satchel: ClothingBackpackSatchel
  #duffelbag: ClothingBackpackDuffel
